[project]
name = "gson-sbc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chembl-webresource-client>=0.10.9",
    "ipykernel>=7.1.0",
    "jupytext>=1.18.1",
    "pandas>=2.3.3",
    "rdkit>=2025.9.1",
]
